<?php

namespace Raspberry\Bundle\MonitorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends EntityRepository
{

    public function findAllOrderedByDate()
    {
        return $this->createQueryBuilder('a')
            ->addOrderBy('a.createdAt', 'DESC');

    }
}
