<?php

namespace Raspberry\Bundle\MonitorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{

    public function findTimes($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.total_time FROM RaspberryMonitorBundle:Log p
                    where  p.site = :id ORDER BY p.createdAt DESC, p.createdAt ASC'
            )->setParameter('id',$id)
            ->setMaxResults(40)
            ->getArrayResult();

    }

    public function findAllOrderedByDate()
    {
        return $this->createQueryBuilder('a')
            ->addOrderBy('a.createdAt', 'DESC');

    }

}
